version: '3.8'

services:
  web:
    build: .
    expose:
      - "5000"
    environment:
      FLASK_ENV: development
    networks:
      - em_net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - em_net

networks:
  em_net:
    driver: bridge
