---
galaxy_info:
  author: Sergey Pozhidaev
  description: Role to distribute files and verify their presence
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - bionic

dependencies: []
